version: "3"
services:

  web:
    build: .
    container_name: web
    ports:
      - "8081:3000"
    links:
      - redis
    environment:
    - REDIS_URL=redis://redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
